### ISSUE TITLE
Missing LICENSE?

### ISSUE THREAD

**Issue by stes** [rajanlab/CURBD#3]
Hi, thanks for sharing your code. I was wondering, did you intentionally publish the code with [No License](https://choosealicense.com/no-permission/) or are you planning to open source the code in the future? Thanks for clarifying.

**Comment by mattperich** [comment]
Thanks for pointing this out! LICENSE file has been added to the repo (GNU GPL).

**Comment by stes** [comment]
Perfect, thanks!
